add getSignMessage in Transaction
bandprotocol/bandchain.js pull request #19
Opened 2021-09-13 10:08 UTC by evilpeach

2021-09-19 15:26 UTC, pzshine requested changes

2021-09-19 15:26 UTC, pzshine commented on src/message.ts
> +import * as jspb from 'google-protobuf'
I think we can import only we use.

2021-09-20 04:53 UTC, pzshine approved these changes
LGTM

2021-09-20 04:57 UTC, taobun approved these changes

2021-09-20 04:57 UTC, merged