Add create data source message
bandprotocol/bandchain.js pull request #25
Opened 2021-11-23 16:15 UTC by pangthebabydustbunny

2021-11-24 10:06 UTC, evilpeach requested changes

2021-11-24 10:06 UTC, evilpeach commented on src/message.ts
> +}
add end line

2021-11-24 10:06 UTC, evilpeach commented on example/react/src/App.tsx
> +const treasury = 'band18e55d9xyrgyg3tk72zmg7s92uu8sd95jzgj73a'
Please use formatter

2021-11-28 18:03 UTC, evilpeach requested changes

2021-11-28 18:03 UTC, evilpeach commented on example/mock/sample_ds.py
> +
It's duplicated in `__tests__` folder

2021-11-28 18:03 UTC, evilpeach commented on example/node/data_source.ts
> +  console.log(executable.length)
forget to remove?

2021-11-28 18:03 UTC, evilpeach commented on example/mock/sample_ds.py
> +        sys.exit(1)
add end line

2021-11-29 06:37 UTC, pangthebabydustbunny commented
please use #27 instead

2021-11-29 06:37 UTC, closed without merging